config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "draw_items#index"
  resources :draw_items
  resources :draw_lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/draw_item.rb
class DrawItem < ApplicationRecord
  belongs_to :draw_list
end

app/models/draw_list.rb
class DrawList < ApplicationRecord
  has_many :draw_items, foreign_key: :draw_list_id, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/draw_items_controller.rb
# frozen_string_literal: true

class DrawItemsController < ApplicationController
  before_action :find_draw_item, only: %i[destroy]
  before_action :find_draw_list, only: %i[new edit index]

  def index
    @draw_lists = DrawList.all
    @draw_items = @draw_list.draw_items if @draw_list
  end

  def new
    @draw_item = @draw_list.draw_items.build
  end

  def create
    @draw_item = DrawItem.new draw_item_params
    if @draw_item.save
      redirect_to draw_lists_path
    else
      render :new
    end
  end

  def destroy
    @draw_item.destroy
    redirect_to draw_lists_path
  end

  private

  def find_draw_item
    @draw_item = DrawItem.find_by(id: params[:id])
    return if @draw_item

    redirect_to new_draw_item_path
  end

  def find_draw_list
    @draw_list = DrawList.find_by(id: params[:draw_list_id])
    return @draw_list
  end

  def draw_item_params
    params.require(:draw_item).permit :fullname, :shortname, :draw_list_id
  end
end

app/controllers/draw_lists_controller.rb
# frozen_string_literal: true

class DrawListsController < ApplicationController
  before_action :find_draw_list, only: %i[show edit update destroy]

  def index
    @draw_lists = DrawList.all
  end

  def show
    @draw_items = @draw_list.draw_items
  end

  def new
    @draw_list = DrawList.new
  end

  def create
    @draw_list = DrawList.new draw_list_params
    if @draw_list.save
      redirect_to draw_lists_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @draw_list.update_attributes! draw_list_params
      redirect_to draw_lists_path
    else
      render :edit
    end
  end

  def destroy
    @draw_list.destroy
    redirect_to draw_lists_path
  end

  private

  def find_draw_list
    @draw_list = DrawList.find_by(id: params[:id])
    return if @draw_list

    redirect_to new_draw_list_path
  end

  def draw_list_params
    params.require(:draw_list).permit :title
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draw_items_helper.rb
module DrawItemsHelper
end

app/views/draw_items/index.html.erb
<div align="center">
  <%= link_to 'List Item', draw_lists_path %>
  <ul>
    <% @draw_lists.each do |draw_list| %>
      <li><%= link_to draw_list.title, draw_items_path(draw_list_id: draw_list.id) %></li>
    <% end %>
  </ul>
  <% if @draw_items && @draw_items.any? %>
    <% draw_items = @draw_items.map(&:shortname).to_json %>
    <%= hidden_field_tag "draw_items", draw_items %>
    <br />
    <table cellpadding="0" cellspacing="0" border="0">
      <tr>
        <td>
          <div class="power_controls">
            <br />
            <br />
            <table class="power" cellpadding="10" cellspacing="0">
              <tr>
                <th align="center">Power</th>
              </tr>
              <tr>
                <td width="78" align="center" id="pw3" onClick="powerSelected(3);">High</td>
              </tr>
              <tr>
                <td align="center" id="pw2" onClick="powerSelected(2);">Med</td>
              </tr>
              <tr>
                <td align="center" id="pw1" onClick="powerSelected(1);">Low</td>
              </tr>
            </table>
            <br />
            <img id="spin_button" src="assets/spin_off.png" alt="Spin" onClick="startSpin();" />
            <br />
            <br />
            &nbsp;&nbsp;<a href="#" onClick="resetWheel(); return false;">Play Again</a><br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(reset)
          </div>
        </td>
        <td width="438" height="582" class="the_wheel" align="center" valign="center">
          <canvas id="canvas" width="434" height="434">
            <p style="{color: white}" align="center">Sorry, your browser doesn't support canvas. Please try another.</p>
          </canvas>
        </td>
      </tr>
    </table>
    <script>
      var draw_items = document.getElementById("draw_items");
      var colors = ['#ee1c24', '#3cb878', '#f6989d', '#00aef0', '#f26522', '#e70697',
        '#fff200', '#f6989d', '#ffffff']
      var segments = []
      JSON.parse(draw_items.value).forEach(function(element){
        segments.push(
          {'fillStyle' : colors[Math.floor(Math.random() * colors.length)], 'text' : element}
        )
      })
      // Create new wheel object specifying the parameters at creation time.
      let theWheel = new Winwheel({
          'outerRadius'     : 212,        // Set outer radius so wheel fits inside the background.
          'innerRadius'     : 75,         // Make wheel hollow so segments don't go all way to center.
          'textFontSize'    : 24,         // Set default font size for the segments.
          'textOrientation' : 'vertical', // Make text vertial so goes down from the outside of wheel.
          'textAlignment'   : 'outer',    // Align text to outside of wheel.
          'numSegments'     : segments.length,         // Specify number of segments.
          'segments'        : segments,
          'animation' :           // Specify the animation to use.
          {
              'type'     : 'spinToStop',
              'duration' : 10,    // Duration in seconds.
              'spins'    : 3,     // Default number of complete spins.
              'callbackFinished' : alertPrize,
              'callbackSound'    : playSound,   // Function to call when the tick sound is to be triggered.
              'soundTrigger'     : 'pin'        // Specify pins are to trigger the sound, the other option is 'segment'.
          },
          'pins' :				// Turn pins on.
          {
              'number'     : 24,
              'fillStyle'  : 'silver',
              'outerRadius': 4,
          }
      });

      // Loads the tick audio sound in to an audio object.
      let audio = new Audio('assets/tick.mp3');

      // This function is called when the sound is to be played.
      function playSound()
      {
          // Stop and rewind the sound if it already happens to be playing.
          audio.pause();
          audio.currentTime = 0;

          // Play the sound.
          audio.play();
      }

      // Vars used by the code in this page to do power controls.
      let wheelPower    = 0;
      let wheelSpinning = false;

      // -------------------------------------------------------
      // Function to handle the onClick on the power buttons.
      // -------------------------------------------------------
      function powerSelected(powerLevel)
      {
          // Ensure that power can't be changed while wheel is spinning.
          if (wheelSpinning == false) {
              // Reset all to grey incase this is not the first time the user has selected the power.
              document.getElementById('pw1').className = "";
              document.getElementById('pw2').className = "";
              document.getElementById('pw3').className = "";

              // Now light up all cells below-and-including the one selected by changing the class.
              if (powerLevel >= 1) {
                  document.getElementById('pw1').className = "pw1";
              }

              if (powerLevel >= 2) {
                  document.getElementById('pw2').className = "pw2";
              }

              if (powerLevel >= 3) {
                  document.getElementById('pw3').className = "pw3";
              }

              // Set wheelPower var used when spin button is clicked.
              wheelPower = powerLevel;

              // Light up the spin button by changing it's source image and adding a clickable class to it.
              document.getElementById('spin_button').src = "assets/spin_on.png";
              document.getElementById('spin_button').className = "clickable";
          }
      }

      // -------------------------------------------------------
      // Click handler for spin button.
      // -------------------------------------------------------
      function startSpin()
      {
          // Ensure that spinning can't be clicked again while already running.
          if (wheelSpinning == false) {
              // Based on the power level selected adjust the number of spins for the wheel, the more times is has
              // to rotate with the duration of the animation the quicker the wheel spins.
              if (wheelPower == 1) {
                  theWheel.animation.spins = 3;
              } else if (wheelPower == 2) {
                  theWheel.animation.spins = 6;
              } else if (wheelPower == 3) {
                  theWheel.animation.spins = 10;
              }

              // Disable the spin button so can't click again while wheel is spinning.
              document.getElementById('spin_button').src       = "assets/spin_off.png";
              document.getElementById('spin_button').className = "";

              // Begin the spin animation by calling startAnimation on the wheel object.
              theWheel.startAnimation();

              // Set to true so that power can't be changed and spin button re-enabled during
              // the current animation. The user will have to reset before spinning again.
              wheelSpinning = true;
          }
      }

      // -------------------------------------------------------
      // Function for reset button.
      // -------------------------------------------------------
      function resetWheel()
      {
          theWheel.stopAnimation(false);  // Stop the animation, false as param so does not call callback function.
          theWheel.rotationAngle = 0;     // Re-set the wheel angle to 0 degrees.
          theWheel.draw();                // Call draw to render changes to the wheel.

          document.getElementById('pw1').className = "";  // Remove all colours from the power level indicators.
          document.getElementById('pw2').className = "";
          document.getElementById('pw3').className = "";

          wheelSpinning = false;          // Reset to false to power buttons and spin can be clicked again.
      }

      // -------------------------------------------------------
      // Called when the spin animation has finished by the callback feature of the wheel because I specified callback in the parameters.
      // -------------------------------------------------------
      function alertPrize(indicatedSegment)
      {
          // Just alert to the user what happened.
          // In a real project probably want to do something more interesting than this with the result.
          if (indicatedSegment.text == 'LOOSE TURN') {
              alert('Sorry but you loose a turn.');
          } else if (indicatedSegment.text == 'BANKRUPT') {
              alert('Oh no, you have gone BANKRUPT!');
          } else {
              alert("You have won " + indicatedSegment.text);
          }
      }
    </script>
  <% end %>
</div>

app/views/draw_items/new.html.erb
<%= form_for @draw_item, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :fullname, "Full name", class: "control-label" %>
    <%= f.text_field :fullname, required: true, autocomplete: :off,
          class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :shortname, "Short name", class: "control-label" %>
    <%= f.text_field :shortname, required: true, autocomplete: :off,
          class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :draw_list_id, "Drarw list id", class: "control-label" %>
    <%= f.text_field :draw_list_id, required: true, autocomplete: :off,
          class: "form-control" %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" do %>
    <i class="fa fa-save"></i> <%= t("action.save") %>
  <% end %>
<% end %>

app/views/draw_lists/edit.html.erb
<%= form_for @draw_list, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title", class: "control-label" %>
    <%= f.text_field :title, required: true, autocomplete: :off,
          class: "form-control" %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" do %>
    <i class="fa fa-save"></i> Save
  <% end %>
<% end %>

app/views/draw_lists/index.html.erb
<%= link_to "Home", root_path %>
<%= link_to "New list", new_draw_list_path %>
<ul>
  <% @draw_lists.each do |draw_list| %>
    <li><%= link_to draw_list.title, draw_list_path(draw_list) %> | <%= link_to "Delete", draw_list_path(draw_list), method: :delete %> |
    <%= link_to "Edit", edit_draw_list_path(draw_list) %></li>
  <% end %>
</ul>

app/views/draw_lists/new.html.erb
<%= form_for @draw_list, html: {class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title", class: "control-label" %>
    <%= f.text_field :title, required: true, autocomplete: :off,
          class: "form-control" %>
  </div>
  <%= f.button :submit, class: "btn btn-primary" do %>
    <i class="fa fa-save"></i> Save
  <% end %>
<% end %>

app/views/draw_lists/show.html.erb
<h2><%= @draw_list.title %></h2>
<%= link_to "New item", new_draw_item_path(draw_list_id: @draw_list.id) %>
<ul>
  <% @draw_items.each do |draw_item| %>
    <li><%= link_to draw_item.fullname, draw_item_path(draw_item) %> | <%= link_to "Delete", draw_item_path(draw_item), method: :delete %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuckyDrawWheel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/latest/TweenMax.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>